project:
  type: website

website:
  title: NeuroShepherd
  site-url: https://neuroshepherd.github.io
  description: "Data science, coding, and statistical programming"
  image: images/neuroshepherd.png
  search: true
  # https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph:
    locale: en_US
  # https://quarto.org/docs/websites/website-llms.html#enabling-llms.txt
  llms-txt: true
  page-footer:
    left: "© 2026 Pat Callahan"
    center: "Built with [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/NeuroShepherd/neuroshepherd.github.io

  navbar:
    title: false
    background: primary
    logo: medium
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - projects.qmd
    right:
      - icon: github
        menu:
          - text: See the Source Code
            href: https://github.com/NeuroShepherd/neuroshepherd.github.io
          - text: Report a Bug
            href: https://github.com/NeuroShepherd/neuroshepherd.github.io/issues
      - icon: rss
        href: posts.xml

format:
  html:
    css:
      - assets/bootstrap-grid.min.css
    theme:
      light: [flatly, brand, _custom.scss]
      dark: [darkly, brand, _custom.scss]
    syntax-highlighting:
      light: github
      dark: arrow
    toc: false
    link-external-newwindow: true
    link-external-icon: true
    # code-links: repo
    anchor-sections: true
    # code-line-numbers: true
    code-link: true
    code-fold: true
    code-summary: "Show Me the Code!"
    code-copy: true
    code-overflow: wrap
