project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
comments:
  giscus: 
    repo: NeuroShepherd/NeuroShepherd.github.io.discussion
    category: "Blog Post Comments"
    mapping: "pathname"



