project:
  type: website

website:
  title: "NeuroShepherd"
  site-url: "https://neuroshepherd.github.io"
  search: true
  description: "A collection of data projects and blog posts about cool programming things"
  page-footer: "Footer in progress"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Website still very much under construction**"
    type: primary
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
    right:
      - icon: rss
        href: posts.xml

      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    # include-after-body: footer.html
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem



