project:
  type: website

website:
  title: "NeuroShepherd Projects"
  site-url: "https://neuroshepherd.github.io"
  description: "A collection of data projects and blog posts about cool programming things"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
    right:
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



