on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Fix permissions for APT cache
        run: sudo chmod -R 777 /var/cache/apt

      - name: Clean up APT cache
        run: sudo apt-get clean
        
      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-dependencies.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff-dev \
            libcairo2-dev \
            libxt-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            zlib1g-dev \
            libv8-dev \
            libglpk-dev \
            librsvg2-bin


      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Install TinyTeX
        run: quarto install tinytex

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}